server {
  listen 3000;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;

  location / {
    add_header Cache-Control "no-store, no-cache, must-revalidate";
    try_files $uri $uri/ /index.html;
  }

  location ~* \.(?:js|css|woff2?|ttf|otf|eot|svg|png|jpg|jpeg|gif|ico|webp)$ {
    add_header Cache-Control "no-cache, must-revalidate";
    access_log off;
  }
}